
window:
  title: "Terminal"
  gtk_theme_variant: "dark"

  dimensions:
    columns: 140
    lines: 40

  padding:
    y: 6
    x: 4

font:
  size: 12.0

  normal:
    family: JetBrainsMonoMedium Nerd Font

  bold:
    family: JetBrainsMonoExtraBold Nerd Font

  italic:
    family: JetBrainsMonoMedium Nerd Font
    style: Medium Italic

theme: One-Dark
colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'

  normal:
    black: '#282c34'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#abb2bf'

  bright:
    black: '#5c6370'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#ffffff'

env:
  TERM: xterm-256color

key_bindings:
  - { key: I, mods: Control, action: ToggleViMode }
  - { key: V, mods: Control, action: Paste }
