shell:
  program: "/usr/bin/zsh"

env:
  TERM: xterm-256color

window:
  title: "Terminal"
  opacity: 0.9
  gtk_theme_variant: "dark"

  dimensions:
    columns: 120
    lines: 32

  padding:
    y: 4
    x: 2

font:
  size: 14.0

  normal:
    family: CaskaydiaCove Nerd Font Mono
    style: Regular

  bold:
    family: CaskaydiaCove Nerd Font Mono
    style: Bold

  italic:
    family: Droid Sans Mono Slashed for Powerline

colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'

  normal:
    black: '#282c34'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#abb2bf'

  bright:
    black: '#5c6370'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#ffffff'
theme: One-Dark
