shell:
  program: /usr/bin/zsh

  args:
    - -c
    - "tmux attach || tmux"

env:
  TERM: xterm-256color

window:
  title: "Terminal"
    
  dimensions:
    columns: 120
    lines: 32

  padding:
    y: 8
    x: 8

cursor:
  style: Underline

font:
  size: 14.0

  normal:
    family: CaskaydiaCove Nerd Font Mono
    style: Regular

  bold:
    family: CaskaydiaCove Nerd Font Mono
    style: Bold

  italic:
    family: Droid Sans Mono Slashed for Powerline

colors:
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  normal:
    black: '#282c34'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#abb2bf'

  bright:
    black: '#5c6370'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#ffffff'


