shell:
  program: /usr/bin/zsh

  args:
    - -c
    - "tmux attach || tmux"

env:
  TERM: xterm-256color


window:
  title: "Terminal"
  opacity: 0.9

  dimensions:
    columns: 120
    lines: 32

  padding:
    y: 4
    x: 2

font:
  size: 14.0

  normal:
    family: CaskaydiaCove Nerd Font Mono
    style: Regular

  bold:
    family: CaskaydiaCove Nerd Font Mono
    style: Bold

  italic:
    family: Droid Sans Mono Slashed for Powerline

colors:
  primary:
    background: '0x0f111a'
    foreground: '0xD8DEE9'

  cursor:
    cursor: '#ffffff'

  normal:
    black:      '0x4C566A'
    red:        '0xBF616A'
    green:      '0xA3BE8C'
    yellow:     '0xEBCB8B'
    blue:       '0x81A1C1'
    magenta:    '0xB48EAD'
    cyan:       '0x88C0D0'
    white:      '0xE5E9F0'
